version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Todo-app-ReactJS
hooks:
  ApplicationStop:
    - location: CD/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: CD/clean_up.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: CD/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: CD/validate_service.sh
      timeout: 300
      runas: root